version: "3.9"

services:
  backend:
    build: ./node
    ports:
      - "3001:3001"
    volumes:
      - ./node:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build: ./react/my-app
    ports:
      - "3000:3000"
    volumes:
      - ./react/my-app:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
